os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
  - ARCH=x86_64 PUID=1000 PGID=1000
  - ARCH=armhf PUID=1001 PGID=1001
  global:
  - secure: Ive9g0HY+2nYnoFUSRvMMEyQFUHjYe/wtyT6S4YRBcwu44DK6jL0xwrosUkBBJHZ9RcGItAHAZ8bw7vOOmzIVmZ91GdidtPG9519rX4Vo/57VFrflWY5ic4vjX+jJxC53ECObPayVJyt76VdxIGqtjYNH4ob7Ay3xu+fvFwPqDXps/WLKRSEwQHDtB6A/taS14vtTqryX5MuEKj+h39MYUkY0fqAkjpMMPq6WZ7b/RYNB+QNV9sbq669xFFBUApzCX71/0bRzMU4er8pd0QVx4YBBuxJyAadzgyNOaiXKTZTCeBd011B5AEnSnKF3qMgOr9wBw/z2sWYHENdoFkbRE1+zBRPpU1miqfytFw1Gz5dS8yMxlFRCE6hR0l4uSxazV1aYLRWhe+v2BRzb3MUhg4/EQNoEhyHBxZT3enGhEPt3hr5lnYyZ37sKBxySMBO8nlO1Osf8h6FLezY63xcBwPruYGQpAGIJpv1M/9pBPxuuYXGim4fdlp2LiDQP0oFvR0L3prtDC1qOxhznWcSc+qdOTtNB0Y+bGgBMouUy3al2Gy5dMerY27L3vdymWpNXLZhUJ/5ngLx7uC3AYqzAEhvZ+3WewR47gXzG1RVc667Qxjw8EjjOThWEu5BsCBvZK3l9aw+vQ9wKjWSH6yeh5BGEKo5YnvSGtX9ppRPMD0=
  - secure: AjJYaOfloCBtsc0hM/kxdEmvidoUxiaQvVJm9Fhc3wURTcLt71urd0cyvtR/7mTeVCaKLWrDic8c451zMWbnxvPkFUmhPrm6kdMjPLzYKzZOSpa37KUeBFfG4U786TPWBqqz9PbJ40SKJhh8SZeMtiWVqSL8rhmGufRZtWupVfW42T4/Ark5dKkzPMX4Sweegl0A8RIyRsVhWRv8P2hJDXgPeHWWCTEZsmURqoPUvobnShAuudDqzIVEZGQiKDT7gOMsgljUjNsh1jNYDlEk51RI4Z3eCFvTmQH1XZYmgsTqKRcQ/m3iZeXpB72GNR/5S/GcigAhfLUkpztt1NC/TwS4LXDUriANbopX3zGbjjJVWK5GJ0qWoOg7GXO0J/1rmcXuKYGNS/Z8Isy3q0ixeSwTPIw1w+ccyBBplNdTvGdfOYikNrGlPZgUTXrjBnJa/pq2cO8OaPorlgA2YMThK1lvvHW1dOT7zQXrxnC0xGgb7ua51fh3I7SYg0lSZ73jx5/y54iQlFD4uAeFjJwQGnSQOpSG6o7Awgf2O1MlXxREPsPsfV4LxO6ZbkEH2uQmYHOGPhnrm3YgKgM/gI9NR+gfB9B3CL1XmwF6J2hpvJRflu3zxVsLuyJNqbfpHv2CQDDHWotWbQiZz5L18eT8tpnGm98X3adfpTz0dyy1MIg=
install: true
before_script:
- docker --version
- make --version
script:
- make ARCH=${ARCH} PUID=${PUID} PGID=${PGID} build test
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} push
after_script:
- docker logout
- make clean
